---
title: "Problem 1"
author: "Weixin Peng & Lu Gan"
date: "November 14, 2017"
output: 
    flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill

---

```{r}
library(tidyverse)
library(janitor)
library(ggplot2)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(flexdashboard)
```
```{r}
data_nynoaa = read_csv("./data/nynoaadat.csv") %>%
  clean_names() %>%
  filter(id == "USC00300085") %>%
  mutate(ymd = date) %>%
  separate(ymd, into = c("year", "month", "day"), sep = "-") %>%
  mutate(
    year = as.factor(year),
    month = as.factor(month),     
    day = as.integer(day),
    tmax = as.integer(tmax),
    tmin = as.integer(tmin)
         ) %>%
  select(id, year, month, tmax, tmin) %>%
  na.omit 
  
```
Column {data-width=650}
-----------------------------------------------------------------------

### The distribution of tmax in each month of observations from USC00300085

```{r}
  data_nynoaa %>%
  group_by(month) %>%
  plot_ly(y = ~tmax, x = ~month, color = ~month, type = "box",
          colors = "Set2")
```

Column {data-width=350}
-----------------------------------------------------------------------

### The scatter plot of mean tmax and tmin in each month of observations from USC00300085

```{r}
data_nynoaa %>%
  group_by(month) %>%
  mutate(mean_tmax_month = mean(tmax, na.rm = TRUE),
         mean_tmin_month = mean(tmin, na.rm = TRUE)) %>%
  plot_ly( x = ~month, y = ~mean_tmax_month, name = 'mean tmax', type = 'scatter', mode = 'markers') %>%
  add_trace(y = ~mean_tmin_month, name = 'mean tmin', mode = 'markers') %>% 
  layout(yaxis = list(title = 'mean tmin(tmax)'))
```

### The number of days with tmax>100 in each month of observations from USC00300085

```{r}
data_nynoaa %>% 
  filter(tmax > 100) %>% 
  count(month) %>% 
  plot_ly(x = ~month, y = ~n, color = ~month, type = "bar") 
```


